### ISSUE TITLE
Dates seem off

### ISSUE THREAD

**Issue by gtauriello** [luispedro/ismb-schedule#2]
This is a beautiful way to browse the program. Thanks for it.
One issue I observed though is that many dates seem off for tracks distributed over multiple days. E.g. all 3D-SIG talks seem to have July 24 as date even though some are on July 25. Same for plenty of the others...

**Comment by luispedro** [comment]
Thanks. This came up on twitter, but I literally just fixed this (updating from Lars' resource)
